apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${{ values.component_id }}-registry-creds
spec:
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  data:
    - secretKey: credentials
      remoteRef:
        key: secrets/janusidp/registry/auth
        property: value
    - secretKey: username
      remoteRef:
        key: secrets/janusidp/registry/username
        property: value
    - secretKey: password
      remoteRef:
        key: secrets/janusidp/registry/password
        property: value
  target:
    name: ${{ values.component_id }}-registry-creds
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "username": "{{ .username }}",
            "password": "{{ .password }}",
            "auths": {
              ${{ values.imageRepository }}: {
                "auth": "{{ .credentials }}"
              }
            }
          }
    creationPolicy: Owner