apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ${{ values.component_id }}-run-pipeline
  namespace: ${{ values.namespace }}
spec:
  params:
    - name: git-revision
      description: The git revision
      default: main
    - name: git-repo-url
      description: The repo url
    - name: output-image
      description: reference of the image that will get created
      default: ${{ values.imageRepository }}/${{ values.quayOrg }}/${{ values.component_id }}
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: ${{ values.component_id }}-pipeline-$(uid)
      spec:
        params:
          - name: source-repo
            value: $(tt.params.git-repo-url)
          - name: source-branch
            value: $(tt.params.git-revision)
          - name: output-image
            value: $(tt.params.output-image)
        pipelineRef:
          name: ${{ values.component_id }}-pipeline
        serviceAccountName: ${{ values.component_id }}-builder
        timeout: 1h0m0s
        workspaces:
          - name: docker-config
            secret:
              secretName: ${{ values.component_id }}-registry-creds
          - name: source-folder
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi