apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: software-templates
  description: A collection of Backstage templates for Janus-IDP Backstage
spec:
  type: url
  targets:
     - https://gitlab-gitlab.apps.cluster-qc7tb.sandbox2129.opentlc.com/rhdh/software-templates/blob/main/scaffolder-templates/quarkus-web-template/template.yaml
     - https://github.com/cooktheryan/dh-ansible/blob/main/scaffolder-templates/go-app/template.yaml
