---
apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.component_id }}-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: 'https://github.com/${{ values.githubOrg }}/${{ values.repoName }}.git'