kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ${{ values.repoName }}
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.repoName }}
    app.kubernetes.io/component: backstage
    backstage.io/kubernetes-id: ${{ values.namespace }}
spec:
  host: ''
  to:
    kind: Service
    name: ${{ values.repoName }}
    weight: 100
  port:
    targetPort: '8080'
  wildcardPolicy: None