---
- name: Automate SNOW 
  hosts: localhost
  gather_facts: false
  collections:
    - servicenow.itsm
  vars:
    username: "{{ lookup('env', 'SN_USERNAME') }}"
    password: "{{ lookup('env', 'SN_PASSWORD') }}"
    instance: "{{ lookup('env', 'SN_HOST') }}"
    token: "{{ lookup('env', 'SLACK_TOKEN') }}"
    short_description: 
    description:

  tasks:
    - name: dump message
      debug:
        var: ansible_eda.event

    - name: Create incident
      servicenow.itsm.incident:
        state: new
        caller: "{{ username }}"
        short_description: "{{ short_description }}"
        description: |
            "{{ description }}"
        impact: low
        urgency: low
      register: new_incident

    - set_fact:
        incident_number_cached: "{{ new_incident.record.number }}"
        cacheable: true

    - debug:
        msg: "A new incident has been created: {{ new_incident.record.number }}"

    - name: Notify Slack that incident has been created
      community.general.slack:
        token: "{{ token }}"
        msg: |
            ```
            #### New Incident ####
            ----------------------------------------------------
            Name: TBD
            Description: TBD

            Need Assistance?
            <https://example.com|Open a ticket>
            ----------------------------------------------------
            ```
        channel: '#dh-ansible'
        color: good
        username: 'rhdh-bot'
        link_names: 0
        parse: 'none'
