---
- name: Automate SNOW Change Request
  hosts: localhost
  gather_facts: false
  collections:
    - servicenow.itsm
  vars:
    username: "{{ lookup('env', 'SN_USERNAME') }}"
    password: "{{ lookup('env', 'SN_PASSWORD') }}"
    instance: "{{ lookup('env', 'SN_HOST') }}"
    short_description:
    description:

  tasks:
    - name: Create a change request
      servicenow.itsm.change_request:
        instance:
          host: "{{ instance }}"
          username: "{{ username }}"
          password: "{{ password }}"
        type: normal
        state: new
        requested_by: "{{ username }}"
        short_description: "{{ short_description }}"
        description: |
            "{{ description }}"
        priority: moderate
        risk: low
        impact: low
      register: change_request

    - name: Close change request as completed
      servicenow.itsm.change_request:
        instance:
          host: "{{ instance }}"
          username: "{{ username }}"
          password: "{{ password }}"
        state: closed
        number: "{{ change_request.record.number }}"
        close_code: successful
        close_notes: "Completed successfully"
      when: change_request.record.state == 'new'

    - name: Get change request record number
      ansible.builtin.debug:
        msg: "A new change request has been created: {{ change_request.record.number }}"

