---
- hosts: localhost
  become: false
  gather_facts: false
  collections:
    - kubernetes.core
  tasks:
  - name: List pvcs
    kubernetes.core.k8s_info:
      kind: PersistentVolumeClaim
      namespace: "{{ namespace }}"
    register: pvc

  - name: Take volumesnapshots of all pvcs
    kubernetes.core.k8s:
      state: present
      definition:
        api_version: snapshot.storage.k8s.io/v1beta1
        kind: VolumeSnapshot
        metadata:
          name: "{{ item }}-snapshot"
          namespace: "{{ namespace }}"
        spec:
         volumeSnapshotClassName: csi-aws-vsc
         source:
           persistentVolumeClaimName: "{{ item }}"
    with_items:
    - "{{ pvc.resources[0].metadata.name }}"
